# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-03 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingListApp', '0004_auto_20161103_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('homelocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShoppingListApp.HomeLocation')),
                ('storelocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShoppingListApp.StoreLocation')),
            ],
        ),
    ]
